import { library, config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {
  faArrowRight,
  faArrowLeft,
  faBars,
  faBell,
  faBolt,
  faBuilding,
  faBox,
  faCalendarDays,
  faCheck,
  faChevronDown,
  faCircleQuestion,
  faClipboard,
  faClock,
  faCreditCard,
  faEnvelope,
  faEye,
  faGaugeHigh,
  faGraduationCap,
  faGlobe,
  faHouse,
  faLocationDot,
  faLock,
  faPhone,
  faPen,
  faPlus,
  faRightFromBracket,
  faRoute,
  faShieldHalved,
  faStar,
  faTruck,
  faUserGroup,
  faVanShuttle,
  faWarehouse,
  faZap,
} from '@fortawesome/free-solid-svg-icons'
import { faApple, faGooglePlay } from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

config.autoAddCss = false

library.add(
  faArrowRight,
  faArrowLeft,
  faBars,
  faBell,
  faBolt,
  faBuilding,
  faBox,
  faCalendarDays,
  faCheck,
  faChevronDown,
  faCircleQuestion,
  faClipboard,
  faClock,
  faCreditCard,
  faEnvelope,
  faEye,
  faGaugeHigh,
  faGraduationCap,
  faGlobe,
  faHouse,
  faLocationDot,
  faLock,
  faPhone,
  faPen,
  faPlus,
  faRightFromBracket,
  faRoute,
  faShieldHalved,
  faStar,
  faTruck,
  faUserGroup,
  faVanShuttle,
  faWarehouse,
  faZap,
  faApple,
  faGooglePlay,
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})
